"""Configuration loading, validation, and merging.

Precedence: CLI flags > environment variables > config.yaml > built-in defaults.
"""

import os
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

from quackaloger.constants import (
    AUDIO_EXTENSIONS,
    AUDIBLE_CATALOG_URL,
    AUDNEXUS_BOOK_URL,
    DEFAULT_AUDIBLE_REQUEST_DELAY,
    DEFAULT_CONFIDENCE_THRESHOLD,
    DEFAULT_GPT_MODEL,
    DEFAULT_MAX_AUDIBLE_CANDIDATES,
    IMAGE_EXTENSIONS,
    TOOL_DIR_NAME,
)

try:
    import yaml
except ImportError:
    yaml = None


# ---------------------------------------------------------------------------
# Config dataclass
# ---------------------------------------------------------------------------

@dataclass
class Config:
    """Frozen configuration for a single run."""

    # Paths
    library_root: str = ""
    tool_dir: str = ""

    # Identification
    confidence_threshold: float = DEFAULT_CONFIDENCE_THRESHOLD
    audible_catalog_url: str = AUDIBLE_CATALOG_URL
    audnexus_url: str = AUDNEXUS_BOOK_URL
    audible_request_delay: float = DEFAULT_AUDIBLE_REQUEST_DELAY
    max_audible_candidates: int = DEFAULT_MAX_AUDIBLE_CANDIDATES
    openai_api_key: str = ""
    openai_model: str = DEFAULT_GPT_MODEL
    enable_ai: bool = True

    # Discovery
    audio_extensions: set = field(default_factory=lambda: set(AUDIO_EXTENSIONS))
    image_extensions: set = field(default_factory=lambda: set(IMAGE_EXTENSIONS))
    ignore_folders: list = field(default_factory=lambda: ["Progression Fantasy Collection Seed"])
    follow_symlinks: bool = False

    # Organization
    series_pattern: str = "{author}/{series}/Book {sequence} - {title} {{{narrator}}}"
    standalone_pattern: str = "{author}/{title} {{{narrator}}}"
    unidentified_action: str = "quarantine"  # "quarantine" or "skip"

    # File operations
    dry_run: bool = True
    embed_markers: bool = True
    trash_dir: str = "trash"
    review_dir: str = "needs-review"

    # Logging
    verbosity: str = "summary"  # "summary", "verbose", "debug"

    # Audible / AI flags (CLI convenience)
    no_audible: bool = False
    no_ai: bool = False
    force: bool = False


# ---------------------------------------------------------------------------
# Default YAML template (written on first run)
# ---------------------------------------------------------------------------

DEFAULT_CONFIG_YAML = """\
# .quackaloger/config.yaml
# Generated by quackaloger on first run.
# Edit any value below. CLI flags override these for one-off runs.

# --- Identification ---
identification:
  # Minimum confidence (0.0-1.0) to accept an Audible match.
  # Below this, the book goes to needs-review/ instead of being organized.
  confidence_threshold: 0.75

  # Audible API settings
  audible_catalog_url: "https://api.audible.com/1.0/catalog/products"
  audnexus_url: "https://api.audnex.us/books"
  audible_request_delay_seconds: 1.0
  max_audible_candidates: 5

  # AI matching (GPT-4o-mini). Set key here or use OPENAI_API_KEY env var.
  openai_api_key: ""
  openai_model: "gpt-4o-mini"
  enable_ai: true

# --- Discovery ---
discovery:
  # File extensions to treat as audiobook files.
  audio_extensions:
    - .mp3
    - .m4b
    - .m4a
    - .flac
    - .ogg
    - .wma
    - .aac
    - .opus

  # Extensions treated as cover art (moved alongside audio).
  image_extensions:
    - .jpg
    - .jpeg
    - .png
    - .webp

  # Folder names to skip entirely during scanning.
  ignore_folders: []

  # Follow symbolic links during scan.
  follow_symlinks: false

# --- Organization ---
organization:
  # Naming pattern for the output directory structure.
  # Tokens: {author}, {series}, {sequence}, {title}, {narrator}
  series_pattern: "{author}/{series}/Book {sequence} - {title} {{{narrator}}}"
  standalone_pattern: "{author}/{title} {{{narrator}}}"

  # What to do with unidentified/low-confidence books.
  # "quarantine" = move to needs-review/
  # "skip" = leave in place, do nothing
  unidentified_action: "quarantine"

# --- File Operations ---
file_operations:
  # Default mode. true = preview only, false = execute.
  dry_run: true

  # Embed a processing marker in audio file metadata after successful organization.
  embed_markers: true

  # Trash bin location (relative to .quackaloger/).
  trash_dir: "trash"

  # Needs-review quarantine directory (relative to .quackaloger/).
  review_dir: "needs-review"

# --- Logging ---
logging:
  # "summary", "verbose", or "debug"
  verbosity: "summary"
"""


# ---------------------------------------------------------------------------
# Loading helpers
# ---------------------------------------------------------------------------

def _ensure_config_file(tool_dir: str) -> str:
    """Create default config.yaml if it doesn't exist. Returns the path."""
    config_path = os.path.join(tool_dir, "config.yaml")
    if not os.path.exists(config_path):
        os.makedirs(tool_dir, exist_ok=True)
        with open(config_path, "w", encoding="utf-8") as f:
            f.write(DEFAULT_CONFIG_YAML)
    return config_path


def _load_yaml(path: str) -> dict:
    if yaml is None:
        return {}
    if not os.path.exists(path):
        return {}
    try:
        with open(path, "r", encoding="utf-8") as f:
            data = yaml.safe_load(f)
        return data if isinstance(data, dict) else {}
    except Exception as e:
        from quackaloger.ui import ui
        ui.warn(f"Could not parse config file {path}: {e}")
        ui.muted("Using built-in defaults.")
        return {}


def _apply_yaml(cfg: Config, data: dict):
    """Overlay YAML values onto the Config dataclass."""
    ident = data.get("identification", {})
    if isinstance(ident, dict):
        if "confidence_threshold" in ident:
            cfg.confidence_threshold = float(ident["confidence_threshold"])
        if "audible_catalog_url" in ident:
            cfg.audible_catalog_url = str(ident["audible_catalog_url"])
        if "audnexus_url" in ident:
            cfg.audnexus_url = str(ident["audnexus_url"])
        if "audible_request_delay_seconds" in ident:
            cfg.audible_request_delay = float(ident["audible_request_delay_seconds"])
        if "max_audible_candidates" in ident:
            cfg.max_audible_candidates = int(ident["max_audible_candidates"])
        if "openai_api_key" in ident and ident["openai_api_key"]:
            cfg.openai_api_key = str(ident["openai_api_key"])
        if "openai_model" in ident:
            cfg.openai_model = str(ident["openai_model"])
        if "enable_ai" in ident:
            cfg.enable_ai = bool(ident["enable_ai"])

    disc = data.get("discovery", {})
    if isinstance(disc, dict):
        if "audio_extensions" in disc and isinstance(disc["audio_extensions"], list):
            cfg.audio_extensions = set(disc["audio_extensions"])
        if "image_extensions" in disc and isinstance(disc["image_extensions"], list):
            cfg.image_extensions = set(disc["image_extensions"])
        if "ignore_folders" in disc and isinstance(disc["ignore_folders"], list):
            cfg.ignore_folders = list(disc["ignore_folders"])
        if "follow_symlinks" in disc:
            cfg.follow_symlinks = bool(disc["follow_symlinks"])

    org = data.get("organization", {})
    if isinstance(org, dict):
        if "series_pattern" in org:
            cfg.series_pattern = str(org["series_pattern"])
        if "standalone_pattern" in org:
            cfg.standalone_pattern = str(org["standalone_pattern"])
        if "unidentified_action" in org:
            cfg.unidentified_action = str(org["unidentified_action"])

    fops = data.get("file_operations", {})
    if isinstance(fops, dict):
        if "dry_run" in fops:
            cfg.dry_run = bool(fops["dry_run"])
        if "embed_markers" in fops:
            cfg.embed_markers = bool(fops["embed_markers"])
        if "trash_dir" in fops:
            cfg.trash_dir = str(fops["trash_dir"])
        if "review_dir" in fops:
            cfg.review_dir = str(fops["review_dir"])

    log = data.get("logging", {})
    if isinstance(log, dict):
        if "verbosity" in log:
            cfg.verbosity = str(log["verbosity"])


def _apply_env(cfg: Config):
    """Override config values from environment variables."""
    key = os.environ.get("ABO_OPENAI_API_KEY") or os.environ.get("OPENAI_API_KEY")
    if key:
        cfg.openai_api_key = key
    url = os.environ.get("ABO_AUDIBLE_CATALOG_URL")
    if url:
        cfg.audible_catalog_url = url
    url = os.environ.get("ABO_AUDNEXUS_URL")
    if url:
        cfg.audnexus_url = url


def _apply_cli(cfg: Config, cli_args: Optional[dict]):
    """Override config values from CLI flags (dict of argparse values)."""
    if cli_args is None:
        return
    if cli_args.get("execute"):
        cfg.dry_run = False
    if cli_args.get("dry_run"):
        cfg.dry_run = True
    if cli_args.get("verbose"):
        cfg.verbosity = "verbose"
    if cli_args.get("debug"):
        cfg.verbosity = "debug"
    if cli_args.get("confidence") is not None:
        cfg.confidence_threshold = float(cli_args["confidence"])
    if cli_args.get("openai_key"):
        cfg.openai_api_key = str(cli_args["openai_key"])
    if cli_args.get("no_ai"):
        cfg.no_ai = True
    if cli_args.get("no_audible"):
        cfg.no_audible = True
    if cli_args.get("force"):
        cfg.force = True


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def config_exists(library_root: str, config_path: str = None) -> bool:
    """Check whether the config file exists without creating it."""
    if config_path:
        return os.path.exists(config_path)
    tool_dir = os.path.join(os.path.abspath(library_root), TOOL_DIR_NAME)
    return os.path.exists(os.path.join(tool_dir, "config.yaml"))


def create_default_config(library_root: str) -> str:
    """Create the default config.yaml and return its path."""
    tool_dir = os.path.join(os.path.abspath(library_root), TOOL_DIR_NAME)
    return _ensure_config_file(tool_dir)


def load_config(
    library_root: str,
    config_path: Optional[str] = None,
    cli_args: Optional[dict] = None,
    auto_create: bool = True,
) -> Config:
    """Build the final Config by merging defaults < YAML < env < CLI.

    If auto_create is True (default), generates config.yaml when missing.
    If False, loads only built-in defaults + env + CLI when the file is absent.
    """
    cfg = Config()
    cfg.library_root = os.path.abspath(library_root)
    cfg.tool_dir = os.path.join(cfg.library_root, TOOL_DIR_NAME)

    os.makedirs(cfg.tool_dir, exist_ok=True)

    if config_path:
        yaml_path = config_path
    elif auto_create:
        yaml_path = _ensure_config_file(cfg.tool_dir)
    else:
        yaml_path = os.path.join(cfg.tool_dir, "config.yaml")

    # Layer 1: YAML file (may not exist if auto_create=False)
    yaml_data = _load_yaml(yaml_path)
    _apply_yaml(cfg, yaml_data)

    # Layer 2: Environment variables
    _apply_env(cfg)

    # Layer 3: CLI flags
    _apply_cli(cfg, cli_args)

    return cfg
